athletes = [
    "COLLET Travis",
    "QUILLET Shawna",
    "THOMAS Geoffrey",
    "MOSER Manon",
    "BASSET Allan",
    "FREART Diane",
    "PINTAPARY Evan",
    "PEYSSON Elise",
    "PRUVOST Malo",
    "MOY Julien",
    "DUTARTE Tristan",
    "GALAS Yassin",
    "BEAUGENDRE Alexis",
    "PHILIPPE Clara",
    "PRIGENT Malo",
    "FURSTOSS Bastien",
    "BEAUFILS Tristan",
    "TANIC Axel",
    "MONNERAIS Gabrielle",
    "PERRUSSEL Alana",
    "SALON Lucien",
    "BRIERE Edana",
    "TOULLIER Jeanne",
    "BEAUGENDRE Adrien",
    "LE TULZO Anais",
    "EL OUARDI Hamza",
    "SEGALOU Anouk",
    "HODOUL Maxime",
    "MANSILA Betuel",
    "CLEMENT Nelson",
    "RANNOU Gabrielle",
    "EL MOUALY Anissa",
    "MOREAC Lucie",
    "HILAIRE Jerry",
    "LOUHAICHI Mehdi",
    "WYCKENS Noalig",
    "ADAINE JEAN-PIERRE Elodie",
    "LOUISE Gabin",
    "LEVALOIS Lilian",
    "TAUDIERE Simon",
    "CLECH Eva",
    "TROHEL Jeanne",
    "ZONGO Glen",
    "BASSET Ophelie",
    "RENAULT Gwenaelle",
    "PRIMA Gaspard",
    "PERESSE Philippine",
    "MORICE Thibo",
    "LEFRANC Anais",
    "VETIER Gireg",
    "TIPHAIGNE Romain",
    "VERHARNE Lea",
    "JEGOUSSE Lea",
    "DUCHEMIN Mickael",
    "BURNEL Lily",
    "PORQUET Alexandre",
    "GALLAIS Bastien",
    "RIOUX Yann",
    "NAYL Capucine",
    "POPHILLAT Louise",
    "ARNAUD-BATTANDIER Iris",
    "HABERT Olivier",
    "JOURDEN Thierry",
    "DJIAN Soliane",
    "LE CALVE Clara",
    "BELGARDE Marina",
    "MAINCENT Elisa",
    "JANVIER Lisa",
    "BEAUVY-MASSON Lena",
    "GUILLO Arzhelenn",
    "ROULLE Julien",
    "JEAN Melvyn",
    "MERCEREAU Louise",
    "DETANTE Adrien",
    "BOUTHELOUP Marie",
    "ROLLAND DERRIEN Arthur",
    "MEINVIELLE Arnaud",
    "CANTAT Titouan",
    "JEGOUSSE Christophe",
    "LAMPE Sandra",
    "BOUSSAMBA ALIBALA Esther Merryl",
    "MAMBA SCHLICK Hugo",
    "COUCHOT Sara",
    "LAWSON Ecclesiaste",
    "POUSSIER Hugo",
    "GUEVELLOU Anna",
    "DRILA Kevin",
    "RAMOTHE Thibault",
    "LAMIRAL Valentine",
    "COUPLIERE Keriwen",
    "HELAUDAIS Annabelle",
    "MEINVIELLE Jacques",
    "GUILBERT Fantine",
    "DESSENNES-VOLTINE Kris",
]
