[project]
name = "sra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=5.4.0",
    "pandas>=2.2.3",
    "streamlit>=1.45.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
